name: Test
on:
  push:
    paths:
      - 'Formula/*'
  pull_request:
    paths:
      - 'Formula/*'

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew audit --strict --formulae Formula/*

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install --formulae Formula/*
    - run: brew test Formula/*
