name: Test
on:
  push:
    paths:
      - ".github/workflows/*"
      - "Formula/*"
  pull_request:
    paths:
      - ".github/workflows/*"
      - "Formula/*"

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew tap-new manlao/tap --no-git
      - run: cp -r Formula/* $(brew --repository)/Library/Taps/manlao/homebrew-tap/Formula
      - run: brew audit --strict --formulae "manlao/tap/node-build-aliases"
      - run: brew audit --strict --formulae "manlao/tap/nodenv-auto-install"

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install --formulae Formula/*
      - run: brew test Formula/*
